# Generated by Django 5.1 on 2024-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='temp_val',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
