# Generated by Django 5.1 on 2024-08-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testreport_temp_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='temp_val',
        ),
    ]
