# Generated by Django 3.2.25 on 2024-04-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_testmodel_num_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
