version: "3.9"

services:
  backend:
    build:
      context: ./spa
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8000
  
  db:
    image: postgres:13-alpine 
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    env_file:
      - .env
      
  proxy:
    build:
      context: ./docker/proxy
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
  
  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping..."
    env_file:
      - .env
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - proxy

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
  postgres-data:
  static-data:
