# Generated by Django 5.1 on 2024-08-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
