# Generated by Django 5.1 on 2024-08-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0002_alter_chapter_description_alter_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
