# Generated by Django 3.2.25 on 2024-04-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorialModule',
            new_name='Tutorial',
        ),
    ]
