# Generated by Django 3.2.25 on 2024-04-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core2', '0002_rename_tutorialmodule_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
