# Generated by Django 3.2.25 on 2024-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
