# Generated by Django 3.2.25 on 2024-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240408_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Freemium'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
