version: '3.8'

services:
    nginx: 
        restart: always
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_volume:/app/backend/django_static
            - media_volume:/app/backend/media
            - ./docker/nginx/production:/etc/nginx/conf.d
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        env_file:
          - .env
        depends_on: 
            - backend
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/nginx/certbot/conf:/etc/letsencrypt
            - ./docker/nginx/certbot/www:/var/www/certbot
        env_file:
          - .env
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/django_static
            - media_volume:/app/backend/media
        expose:
            - 8000
        env_file:
          - .env 
        depends_on:
          - db 
    db:
        image: postgres:13-alpine 
        restart: always
        volumes:
          - postgres_data:/var/lib/postgresql/data 
        environment: 
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        env_file:
          - .env

volumes:
    static_volume: {}
    postgres_data: {}
    media_volume: {}