# Generated by Django 3.2.25 on 2024-04-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='num_questions',
            field=models.IntegerField(default=27),
        ),
    ]
